# Generated by Django 4.0.2 on 2022-04-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='laptop',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
