# Generated by Django 4.0.2 on 2022-04-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_laptop_description_laptop_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('clothes_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('material', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default=0)),
                ('images', models.ImageField(default=None, null=b'I00\n', upload_to='image')),
                ('description', models.CharField(default='', max_length=1000)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mobilephone',
            fields=[
                ('mobile_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('material', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default=0)),
                ('model', models.CharField(default='', max_length=100)),
                ('images', models.ImageField(default=None, null=b'I00\n', upload_to='image')),
                ('description', models.CharField(default='', max_length=1000)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
