# Generated by Django 4.0.2 on 2022-04-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_clothes_mobilephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('product_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.category'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.category'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.category'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.category'),
        ),
    ]
