# Generated by Django 4.0.2 on 2022-04-13 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_category_book_category_id_clothes_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Product.category'),
        ),
    ]
