# Generated by Django 4.0.2 on 2022-04-13 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0007_clothes_mobilephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('book_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.book')),
            ],
        ),
    ]
