# Generated by Django 4.0.2 on 2022-04-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_category_book_category_id_clothes_category_id_and_more'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='clothes_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.clothes'),
        ),
        migrations.AddField(
            model_name='cart',
            name='laptop_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.laptop'),
        ),
        migrations.AddField(
            model_name='cart',
            name='mobile_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.mobilephone'),
        ),
    ]
