# Generated by Django 4.0.2 on 2022-04-13 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0002_cart_clothes_id_cart_laptop_id_cart_mobile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='clothes_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='laptop_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='mobile_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
