# Generated by Django 4.0.2 on 2022-05-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(default=None, max_length=100)),
                ('shipmentment_id', models.CharField(default=None, max_length=100)),
                ('user', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(default=None, max_length=100)),
                ('totalprice', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('address', models.CharField(default=None, max_length=100)),
                ('price', models.FloatField(default=None)),
            ],
        ),
    ]
