# Generated by Django 4.0.2 on 2022-05-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_order_payment_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='price',
        ),
        migrations.AddField(
            model_name='shipment',
            name='method_transport',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
