# Generated by Django 4.0.2 on 2022-05-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_remove_shipment_price_shipment_method_transport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipmentment_id',
            new_name='shipment_id',
        ),
    ]
